[build-system]
requires = [ "hatchling","versioningit" ]
build-backend = "hatchling.build"

[project]
name = "mctpy"
#version = "0.0.1"
description = "MCT solver package in python"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]

[tool.hatch.version]
source = "versioningit"

[tool.versioningit]
#version = {attr = "version_query.local_git_version.PREDICTED"}

authors = [
  { name = "thvoigtmann", email = "thomas.voigtmann@dlr.de" },
]

classifiers = [
]

dependencies = [
    "numpy",
    "scipy",
    "numba",
    "h5py",
]

[project.urls]
"Homepage" = "https://github.com/thvoigtmann/mctpy"

[project.optional-dependencies]
dev = [
    "sphinx",
    "sphinx-rtd-theme",
]
